=== junganghu/netfpga_1g_httpGET/lib/xml/NF2_register_system.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.NetFPGA.org/NF2_register_system" targetNamespace="http://www.NetFPGA.org/NF2_register_system" elementFormDefault="qualified">

  <complexType name="Constant">
    <sequence>
      <element name="name" type="string" maxOccurs="1" minOccurs="1">
        </element>
      <element name="description" type="string" maxOccurs="1" minOccurs="0">
        </element>
      <element name="width" type="tns:Expression" maxOccurs="1" minOccurs="0">
        </element>
      <element name="value" type="tns:Expression" maxOccurs="1" minOccurs="1">
        </element>
    </sequence>
  </complexType>

  <complexType name="SimpleType">
    <complexContent>
      <extension base="tns:Type">
        <sequence>
          <element name="width" type="tns:Expression" maxOccurs="1" minOccurs="1">
            </element>
          <element name="bitmask" type="tns:BitmaskType" maxOccurs="unbounded" minOccurs="0">
            </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="BitmaskType">
    <complexContent>
      <extension base="tns:Type">
        <choice maxOccurs="1" minOccurs="1">
          <element name="pos" type="int" maxOccurs="1" minOccurs="1">
             </element>
          <sequence>
            <element name="pos_lo" type="int" maxOccurs="1" minOccurs="1">
               </element>
            <element name="pos_hi" type="int" maxOccurs="1" minOccurs="1">
               </element>
          </sequence>
        </choice>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="CompoundType">
    <complexContent>
      <extension base="tns:Type">
        <sequence>
          <element name="field" type="tns:Field" maxOccurs="unbounded" minOccurs="1"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="Field">
    <sequence>
      <element name="name" type="string" maxOccurs="1" minOccurs="1">
        </element>
      <element name="description" type="string" maxOccurs="1" minOccurs="0"/>
      <choice maxOccurs="1" minOccurs="1">
        <element name="type" type="string" maxOccurs="1" minOccurs="1">
          </element>
        <element name="width" type="tns:Expression" maxOccurs="1" minOccurs="1">
          </element>
      </choice>
    </sequence>
  </complexType>

  <complexType name="Type">
    <sequence>
      <element name="name" type="string" maxOccurs="1" minOccurs="1">
        </element>
      <element name="description" type="string" maxOccurs="1" minOccurs="0"/>
    </sequence>
  </complexType>

  <complexType name="TableType">
    <complexContent>
      <extension base="tns:Type">
        <sequence>
          <element name="depth" type="int" maxOccurs="1" minOccurs="1"/>
          <choice maxOccurs="1" minOccurs="1">
            <element name="entry_type" type="string" maxOccurs="1" minOccurs="1"/>
            <element name="width" type="tns:Expression" maxOccurs="1" minOccurs="1"/>
          </choice>
        </sequence>
        <attribute name="table_type">
          <simpleType>
            <restriction base="string">
              <enumeration value="indirect"/>
            </restriction>
          </simpleType>
        </attribute>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="Register">
    <sequence>
      <element name="name" type="string" maxOccurs="1" minOccurs="1">
        </element>
      <element name="description" type="string" maxOccurs="1" minOccurs="0">
        </element>
      <choice maxOccurs="1" minOccurs="0">
        <element name="type" type="string" maxOccurs="1" minOccurs="1">
          </element>
        <element name="width" type="tns:Expression" maxOccurs="1" minOccurs="1"/>
      </choice>
    </sequence>
  </complexType>

  <complexType name="RegisterList">
    <element name="register" type="tns:Register" maxOccurs="unbounded" minOccurs="0">
      </element>
    <element name="register_group" type="tns:RegisterGroup" maxOccurs="unbounded" minOccurs="0">
      </element>
  </complexType>

  <complexType name="Module">
    <sequence>
      <element name="name" type="string" maxOccurs="1" minOccurs="1">
        </element>
      <element name="prefix" type="string" maxOccurs="1" minOccurs="1">
        </element>
      <element name="location" maxOccurs="1" minOccurs="1">
        <simpleType>
          <restriction base="string">
            <enumeration value="core"/>
            <enumeration value="udp"/>
            <enumeration value="cpci"/>
          </restriction>
        </simpleType>
      </element>
      <element name="description" type="string" maxOccurs="1" minOccurs="0">
        </element>
      <element name="blocksize" type="string" maxOccurs="1" minOccurs="0">
        </element>
      <choice>
        <element name="preferred_base" type="tns:Address" maxOccurs="1" minOccurs="0">
          </element>
        <element name="force_base" type="tns:Address" maxOccurs="1" minOccurs="0">
          </element>
      </choice>
      <element name="registers" type="tns:RegisterList" maxOccurs="1" minOccurs="0"/>
      <element name="constants" type="tns:ConstantList" maxOccurs="1" minOccurs="0"/>
      <element name="types" type="tns:TypeList" maxOccurs="1" minOccurs="0"/>
      <element name="use_shared" type="string" maxOccurs="1" minOccurs="0"/>
        </element>
    </sequence>
  </complexType>

  <complexType name="RegisterGroup">
    <sequence>
      <element name="name" type="string" maxOccurs="1" minOccurs="1">
      	</element>
      <element name="description" type="string" maxOccurs="1" minOccurs="0">
        </element>
      <element name="instances" type="tns:Expression" maxOccurs="1" minOccurs="1">
      	</element>
      <element name="instance_size" type="tns:Expression" maxOccurs="1" minOccurs="0"/>
      <element name="register" type="tns:Register" maxOccurs="unbounded" minOccurs="0">
      	</element>
    </sequence>
  </complexType>

  <complexType name="Project">
    <sequence>
      <element name="name" type="string" maxOccurs="1" minOccurs="1">
        </element>
      <element name="description" type="string" maxOccurs="1" minOccurs="0">
        </element>
      <element name="version_major" type="int" maxOccurs="1" minOccurs="0">
        </element>
      <element name="version_minor" type="int" maxOccurs="1" minOccurs="0">
        </element>
      <element name="version_revision" type="int" maxOccurs="1" minOccurs="0">
        </element>
      <element name="dev_id" type="int" maxOccurs="1" minOccurs="0">
        </element>
      <element name="constants" type="tns:ConstantList" maxOccurs="1" minOccurs="0"/>
      <element name="types" type="tns:TypeList" maxOccurs="1" minOccurs="0"/>
      <element name="use_modules" type="string" maxOccurs="1" minOccurs="0">
        </element>
      <element name="memalloc" type="tns:MemoryAllocation" maxOccurs="1" minOccurs="1">
        </element>
    </sequence>
  </complexType>

  <attribute name="path" type="string"/>
  <simpleType name="Address">
    <restriction base="tns:hex"/>
  </simpleType>

  <complexType name="ConstantList">
    <sequence>
      <element name="constant" type="tns:Constant" maxOccurs="unbounded" minOccurs="0"/>
    </sequence>
  </complexType>

  <complexType name="TypeList">
    <sequence>
      <element name="type" type="tns:Type" maxOccurs="unbounded" minOccurs="0"/>
    </sequence>
  </complexType>

  <element name="module" type="tns:Module"/>
  <element name="project" type="tns:Project"/>

  <complexType name="Global">
    <sequence>
      <element name="constants" type="tns:ConstantList"/>
      <element name="types" type="tns:TypeList"/>
    </sequence>
  </complexType>

  <element name="global" type="tns:Global"/>

  <complexType name="Shared">
    <sequence>
      <element name="description" type="string" maxOccurs="1" minOccurs="0"/>
      <element name="constants" type="tns:ConstantList" maxOccurs="1" minOccurs="0"/>
      <element name="types" type="tns:TypeList" maxOccurs="1" minOccurs="0"/>
    </sequence>
  </complexType>

  <element name="shared" type="tns:Shared"/>

  <simpleType name="IntOrConstant">
    <union memberTypes="string int"/>
  </simpleType>

  <simpleType name="hex">
    <restriction base="string">
      <pattern value="0[xX][0-9a-fA-F]+"/>
    </restriction>
  </simpleType>

  <simpleType name="intOrHex">
    <union memberTypes="int tns:hex"/>
  </simpleType>

  <simpleType name="Expression">
    <restriction base="string"/>
  </simpleType>

  <simpleType name="MemoryLayout">
    <restriction base="string">
      <enumeration value="reference"/>
      <enumeration value="freeform"/>
      <enumeration value="cpci"/>
    </restriction>
  </simpleType>

  <complexType name="MemoryAllocation">
    <sequence>
      <element name="group" type="tns:MemoryAllocationGroup" maxOccurs="unbounded" minOccurs="0">
    		</element>
    </sequence>
    <attribute name="layout" type="tns:MemoryLayout" use="required"/>
  </complexType>

  <complexType name="MemoryAllocationGroup">
    <sequence>
      <element name="instance" type="tns:ModuleInstance" maxOccurs="unbounded" minOccurs="0">
    		</element>
    </sequence>
    <attribute name="name" type="string" use="required"/>
  </complexType>

  <complexType name="ModuleInstance">
    <attribute name="name" type="string" use="required"/>
    <attribute name="count" type="string" use="optional"/>
    <attribute name="base" type="tns:Address" use="optional"/>
  </complexType>
</schema>

=== junganghu/netfpga_1g_httpGET/projects/openflow_switch/include/exact_match.xml
<?xml version="1.0" encoding="UTF-8"?>
<nf:module xmlns:nf="http://www.NetFPGA.org/NF2_register_system" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.NetFPGA.org/NF2_register_system NF2_register_system.xsd ">
	<nf:name>exact_match</nf:name>
	<nf:prefix>exact_match</nf:prefix>
	<nf:location>udp</nf:location>
	<nf:description>exact match lookup</nf:description>
	<nf:blocksize>64</nf:blocksize>
	<nf:registers>
	</nf:registers>
	<nf:constants>
		<nf:constant>
			<nf:name>:OPENFLOW_EXACT_ENTRY_PKT_COUNTER_WIDTH</nf:name>
			<nf:value>25</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_EXACT_ENTRY_PKT_COUNTER_POS</nf:name>
			<nf:value>0</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_EXACT_ENTRY_LAST_SEEN_WIDTH</nf:name>
			<nf:value>7</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_EXACT_ENTRY_LAST_SEEN_POS</nf:name>
			<nf:value>25</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_EXACT_ENTRY_BYTE_COUNTER_WIDTH</nf:name>
			<nf:value>32</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_EXACT_ENTRY_BYTE_COUNTER_POS</nf:name>
			<nf:value>32</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_EXACT_ENTRY_HDR_BASE_POS</nf:name>
			<nf:value>0x0</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_EXACT_ENTRY_COUNTERS_POS</nf:name>
			<nf:value>0x8</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_EXACT_ENTRY_ACTION_BASE_POS</nf:name>
			<nf:value>0xa</nf:value>
		</nf:constant>
	</nf:constants>
	<nf:types>
	</nf:types>
</nf:module>

=== junganghu/netfpga_1g_httpGET/projects/cpci_reprogrammer/include/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<nf:project xmlns:nf="http://www.NetFPGA.org/NF2_register_system" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.NetFPGA.org/NF2_register_system NF2_register_system.xsd ">
  <nf:name>CPCI Reprogrammer</nf:name>
  <nf:description>CPCI Reprogrammer</nf:description>
  <nf:version_major>1</nf:version_major>
  <nf:version_minor>0</nf:version_minor>
  <nf:version_revision>1</nf:version_revision>
  <nf:dev_id>4</nf:dev_id>
  <nf:use_modules>
    core/nf2/generic_top
    core/nf2/reference_core
    core/cpci_bus
    core/utils
  </nf:use_modules>-
  <nf:memalloc layout="reference">
    <nf:group name="core1">
      <nf:instance name="device_id" />
    </nf:group>
  </nf:memalloc>
</nf:project>

=== junganghu/netfpga_1g_httpGET/projects/openflow_switch/include/match_arbiter.xml
<?xml version="1.0" encoding="UTF-8"?>
<nf:module xmlns:nf="http://www.NetFPGA.org/NF2_register_system" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.NetFPGA.org/NF2_register_system NF2_register_system.xsd ">
	<nf:name>match_arbiter</nf:name>
	<nf:prefix>match_arbiter</nf:prefix>
	<nf:location>udp</nf:location>
	<nf:description>Arbitration between exact and wildcard lookups results</nf:description>
	<nf:blocksize>64</nf:blocksize>
	<nf:registers>
	</nf:registers>
	<nf:constants>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_TRANSP_DST_WIDTH</nf:name>
			<nf:value>16</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_TRANSP_DST_POS</nf:name>
			<nf:value>0</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_TRANSP_SRC_WIDTH</nf:name>
			<nf:value>16</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_TRANSP_SRC_POS</nf:name>
			<nf:value>:OPENFLOW_ENTRY_TRANSP_DST_POS + :OPENFLOW_ENTRY_TRANSP_DST_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_IP_PROTO_WIDTH</nf:name>
			<nf:value>8</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_IP_PROTO_POS</nf:name>
			<nf:value>:OPENFLOW_ENTRY_TRANSP_SRC_POS + :OPENFLOW_ENTRY_TRANSP_SRC_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_IP_DST_WIDTH</nf:name>
			<nf:value>32</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_IP_DST_POS</nf:name>
			<nf:value>:OPENFLOW_ENTRY_IP_PROTO_POS + :OPENFLOW_ENTRY_IP_PROTO_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_IP_SRC_WIDTH</nf:name>
			<nf:value>32</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_IP_SRC_POS</nf:name>
			<nf:value>:OPENFLOW_ENTRY_IP_DST_POS + :OPENFLOW_ENTRY_IP_DST_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_ETH_TYPE_WIDTH</nf:name>
			<nf:value>16</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_ETH_TYPE_POS</nf:name>
			<nf:value>:OPENFLOW_ENTRY_IP_SRC_POS + :OPENFLOW_ENTRY_IP_SRC_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_ETH_DST_WIDTH</nf:name>
			<nf:value>48</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_ETH_DST_POS</nf:name>
			<nf:value>:OPENFLOW_ENTRY_ETH_TYPE_POS + :OPENFLOW_ENTRY_ETH_TYPE_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_ETH_SRC_WIDTH</nf:name>
			<nf:value>48</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_ETH_SRC_POS</nf:name>
			<nf:value>:OPENFLOW_ENTRY_ETH_DST_POS + :OPENFLOW_ENTRY_ETH_DST_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_SRC_PORT_WIDTH</nf:name>
			<nf:value>8</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_SRC_PORT_POS</nf:name>
			<nf:value>:OPENFLOW_ENTRY_ETH_SRC_POS + :OPENFLOW_ENTRY_ETH_SRC_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_IP_TOS_WIDTH</nf:name>
			<nf:value>8</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_IP_TOS_POS</nf:name>
			<nf:value>:OPENFLOW_ENTRY_SRC_PORT_POS + :OPENFLOW_ENTRY_SRC_PORT_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_VLAN_ID_WIDTH</nf:name>
			<nf:value>16</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_VLAN_ID_POS</nf:name>
			<nf:value>:OPENFLOW_ENTRY_IP_TOS_POS + :OPENFLOW_ENTRY_IP_TOS_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ENTRY_WIDTH</nf:name>
			<nf:value>248</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_ACTION_WIDTH</nf:name>
			<nf:description>The actionfield is composed of a bitmask specifying actions to take and arguments.</nf:description>
			<nf:value>320</nf:value>
		</nf:constant>

		<nf:constant>
			<nf:name>:OPENFLOW_FORWARD_BITMASK_WIDTH</nf:name>
			<nf:description>Ports to forward on</nf:description>
			<nf:value>16</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_FORWARD_BITMASK_POS</nf:name>
			<nf:value>0</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_NF2_ACTION_FLAG_WIDTH</nf:name>
			<nf:value>16</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_NF2_ACTION_FLAG_POS</nf:name>
			<nf:value>:OPENFLOW_FORWARD_BITMASK_POS + :OPENFLOW_FORWARD_BITMASK_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_VLAN_VID_WIDTH</nf:name>
			<nf:description>Vlan ID to be replaced</nf:description>
			<nf:value>16</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_VLAN_VID_POS</nf:name>
			<nf:value>:OPENFLOW_NF2_ACTION_FLAG_POS + :OPENFLOW_NF2_ACTION_FLAG_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_VLAN_PCP_WIDTH</nf:name>
			<nf:description>Vlan priority to be replaced</nf:description>
			<nf:value>8</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_VLAN_PCP_POS</nf:name>
			<nf:value>:OPENFLOW_SET_VLAN_VID_POS + :OPENFLOW_SET_VLAN_VID_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_DL_SRC_WIDTH</nf:name>
			<nf:description>Source MAC address to be replaced</nf:description>
			<nf:value>48</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_DL_SRC_POS</nf:name>
			<nf:value>:OPENFLOW_SET_VLAN_PCP_POS + :OPENFLOW_SET_VLAN_PCP_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_DL_DST_WIDTH</nf:name>
			<nf:description>Destination MAC address to be replaced</nf:description>
			<nf:value>48</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_DL_DST_POS</nf:name>
			<nf:value>:OPENFLOW_SET_DL_SRC_POS + :OPENFLOW_SET_DL_SRC_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_NW_SRC_WIDTH</nf:name>
			<nf:description>Source network address to be replaced</nf:description>
			<nf:value>32</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_NW_SRC_POS</nf:name>
			<nf:value>:OPENFLOW_SET_DL_DST_POS + :OPENFLOW_SET_DL_DST_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_NW_DST_WIDTH</nf:name>
			<nf:description>Destination network address to be replaced</nf:description>
			<nf:value>32</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_NW_DST_POS</nf:name>
			<nf:value>:OPENFLOW_SET_NW_SRC_POS + :OPENFLOW_SET_NW_SRC_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_NW_TOS_WIDTH</nf:name>
			<nf:description>TOS to be replaced</nf:description>
			<nf:value>8</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_NW_TOS_POS</nf:name>
			<nf:value>:OPENFLOW_SET_NW_DST_POS + :OPENFLOW_SET_NW_DST_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_TP_SRC_WIDTH</nf:name>
			<nf:description>Source transport port to be replaced</nf:description>
			<nf:value>16</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_TP_SRC_POS</nf:name>
			<nf:value>:OPENFLOW_SET_NW_TOS_POS + :OPENFLOW_SET_NW_TOS_WIDTH</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_TP_DST_WIDTH</nf:name>
			<nf:description>Destination transport port to be replaced</nf:description>
			<nf:value>16</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_SET_TP_DST_POS</nf:name>
			<nf:value>:OPENFLOW_SET_TP_SRC_POS + :OPENFLOW_SET_TP_SRC_WIDTH</nf:value>
		</nf:constant>
	</nf:constants>
	<nf:types>
	</nf:types>
</nf:module>

=== junganghu/netfpga_1g_httpGET/projects/openflow_switch/include/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<nf:project xmlns:nf="http://www.NetFPGA.org/NF2_register_system" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.NetFPGA.org/NF2_register_system NF2_register_system.xsd ">
  <nf:name>OpenFlow Switch</nf:name>
  <nf:description>OpenFlow Switch</nf:description>
  <nf:version_major>1</nf:version_major>
  <nf:version_minor>0</nf:version_minor>
  <nf:version_revision>4</nf:version_revision>
  <nf:dev_id>0</nf:dev_id>
  <nf:use_modules>
    core/io_queues/cpu_dma_queue
    core/io_queues/ethernet_queue
    contrib/ucsd/gig_eth_mac
    core/input_arbiter/rr_input_arbiter
    core/nf2/generic_top
    core/nf2/reference_core
    core/user_data_path/reference_user_data_path
    core/user_data_path/udp_reg_master
    core/output_queues/bram_output_queues
    core/io/mdio
    core/cpci_bus
    core/dma
    core/io_queues/add_rm_hdr
    core/utils/generic_regs
    core/utils
  </nf:use_modules>
  <nf:memalloc layout="reference">
    <nf:group name="core1">
      <nf:instance name="device_id" />
      <nf:instance name="dma" base="0x0500000"/>
      <nf:instance name="mdio" base="0x0440000"/>
      <nf:instance name="nf2_mac_grp" count="4" />
      <nf:instance name="cpu_dma_queue" count="4" />
    </nf:group>
    <nf:group name="udp">
      <nf:instance name="in_arb" base="0x02000100"/>
      <nf:instance name="vlan_remover" />
      <nf:instance name="header_parser" />
      <nf:instance name="top_ddos" />
      <nf:instance name="exact_match" />
      <nf:instance name="watchdog" base="0x02001400"/>
      <nf:instance name="match_arbiter" />
      <nf:instance name="openflow_output_port_lookup" base="0x02000000"/>
      <nf:instance name="opl_processor" />
      <nf:instance name="wildcard_match" base="0x02001000"/>
      <nf:instance name="bram_output_queues" base="0x02000300"/>
    </nf:group>
  </nf:memalloc>
</nf:project>

=== junganghu/netfpga_1g_httpGET/projects/openflow_switch/include/top_ddos.xml
<?xml version="1.0" encoding="UTF-8"?>
<nf:module xmlns:nf="http://www.NetFPGA.org/NF2_register_system" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.NetFPGA.org/NF2_register_system NF2_register_system.xsd ">
	<nf:name>top_ddos</nf:name>
	<nf:prefix>top_ddos</nf:prefix>
	<nf:location>udp</nf:location>
	<nf:description>Registers for Clock controller Module</nf:description>
	<nf:blocksize>64</nf:blocksize>
	<nf:registers>
		<nf:register>
		  <nf:name>THRESHOLD</nf:name>
			<nf:description>Threshold to detect bot IP</nf:description>
			<nf:type>generic_software32</nf:type>
		</nf:register>
		<nf:register>
		  <nf:name>MAX_COUNT</nf:name>
			<nf:description>Max value of flush_1s counter</nf:description>
			<nf:type>generic_software32</nf:type>
		</nf:register>
		<nf:register>
		  <nf:name>CONTROL_MODE</nf:name>
			<nf:description>Mode options to clock bot IP</nf:description>
			<nf:type>generic_software32</nf:type>
		</nf:register>
		<nf:register>
		  <nf:name>FLUSH_SIGNAL</nf:name>
			<nf:description>clock flushing hash table</nf:description>
			<nf:type>generic_hardware32</nf:type>
		</nf:register>
		<nf:register>
		  <nf:name>COUNT_1</nf:name>
			<nf:description>The Key value used by the Clock Controller Module</nf:description>
			<nf:type>generic_hardware32</nf:type>
		</nf:register>
		<nf:register>
		  <nf:name>SRC_IP_1</nf:name>
			<nf:description>The Key value used by the Clock Controller Module</nf:description>
			<nf:type>generic_hardware32</nf:type>
		</nf:register>
		<nf:register>
		  <nf:name>DETECTED_IP</nf:name>
			<nf:description>The Key value used by the Clock Controller Module</nf:description>
			<nf:type>generic_hardware32</nf:type>
		</nf:register>
	</nf:registers>
	<nf:constants>
	</nf:constants>
	<nf:types>		
	</nf:types>
</nf:module>

=== junganghu/netfpga_1g_httpGET/projects/openflow_switch/include/opl_processor.xml
<?xml version="1.0" encoding="UTF-8"?>
<nf:module xmlns:nf="http://www.NetFPGA.org/NF2_register_system" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.NetFPGA.org/NF2_register_system NF2_register_system.xsd ">
	<nf:name>opl_processor</nf:name>
	<nf:prefix>opl_processor</nf:prefix>
	<nf:location>udp</nf:location>
	<nf:description>opl_processor</nf:description>
	<nf:blocksize>64</nf:blocksize>
	<nf:registers>
	</nf:registers>
	<nf:constants>
		<nf:constant>
			<nf:name>:NF2_OFPAT_OUTPUT</nf:name>
			<nf:width>:OPENFLOW_NF2_ACTION_FLAG_WIDTH</nf:width>
			<nf:value>0x0001</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:NF2_OFPAT_SET_VLAN_VID</nf:name>
			<nf:width>:OPENFLOW_NF2_ACTION_FLAG_WIDTH</nf:width>
			<nf:value>0x0002</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:NF2_OFPAT_SET_VLAN_PCP</nf:name>
			<nf:width>:OPENFLOW_NF2_ACTION_FLAG_WIDTH</nf:width>
			<nf:value>0x0004</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:NF2_OFPAT_STRIP_VLAN</nf:name>
			<nf:width>:OPENFLOW_NF2_ACTION_FLAG_WIDTH</nf:width>
			<nf:value>0x0008</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:NF2_OFPAT_SET_DL_SRC</nf:name>
			<nf:width>:OPENFLOW_NF2_ACTION_FLAG_WIDTH</nf:width>
			<nf:value>0x0010</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:NF2_OFPAT_SET_DL_DST</nf:name>
			<nf:width>:OPENFLOW_NF2_ACTION_FLAG_WIDTH</nf:width>
			<nf:value>0x0020</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:NF2_OFPAT_SET_NW_SRC</nf:name>
			<nf:width>:OPENFLOW_NF2_ACTION_FLAG_WIDTH</nf:width>
			<nf:value>0x0040</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:NF2_OFPAT_SET_NW_DST</nf:name>
			<nf:width>:OPENFLOW_NF2_ACTION_FLAG_WIDTH</nf:width>
			<nf:value>0x0080</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:NF2_OFPAT_SET_NW_TOS</nf:name>
			<nf:width>:OPENFLOW_NF2_ACTION_FLAG_WIDTH</nf:width>
			<nf:value>0x0100</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:NF2_OFPAT_SET_TP_SRC</nf:name>
			<nf:width>:OPENFLOW_NF2_ACTION_FLAG_WIDTH</nf:width>
			<nf:value>0x0200</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:NF2_OFPAT_SET_TP_DST</nf:name>
			<nf:width>:OPENFLOW_NF2_ACTION_FLAG_WIDTH</nf:width>
			<nf:value>0x0400</nf:value>
		</nf:constant>
	</nf:constants>
	<nf:types>
	</nf:types>
</nf:module>

=== junganghu/netfpga_1g_httpGET/projects/openflow_switch/include/vlan_remover.xml
<?xml version="1.0" encoding="UTF-8"?>
<nf:module xmlns:nf="http://www.NetFPGA.org/NF2_register_system" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.NetFPGA.org/NF2_register_system NF2_register_system.xsd ">
	<nf:name>vlan_remover</nf:name>
	<nf:prefix>vlan_remover</nf:prefix>
	<nf:location>udp</nf:location>
	<nf:description>Remove vlan tag and ethtype if ethtype is vlan, and store them into module header</nf:description>
	<nf:blocksize>64</nf:blocksize>
	<nf:registers>
	</nf:registers>
	<nf:constants>
		<nf:constant>
			<nf:name>:VLAN_CTRL_WORD</nf:name>
			<nf:width>8</nf:width>
			<nf:value>0x42</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:VLAN_ETHERTYPE</nf:name>
			<nf:width>16</nf:width>
			<nf:value>0x8100</nf:value>
		</nf:constant>
	</nf:constants>
	<nf:types>
	</nf:types>
</nf:module>

=== junganghu/netfpga_1g_httpGET/projects/openflow_switch/include/output_port_lookup.xml
<?xml version="1.0" encoding="UTF-8"?>
<nf:module xmlns:nf="http://www.NetFPGA.org/NF2_register_system" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.NetFPGA.org/NF2_register_system NF2_register_system.xsd ">
	<nf:name>openflow_output_port_lookup</nf:name>
	<nf:prefix>openflow_lookup</nf:prefix>
	<nf:location>udp</nf:location>
	<nf:description>Output Port Lookup for OpenFlow hardware datapath</nf:description>
	<nf:blocksize>256</nf:blocksize>
	<nf:registers>
		<nf:register>
			<nf:name>wildcard_misses</nf:name>
			<nf:description>Wildcard match miss counter</nf:description>
			<nf:type>generic_counter32</nf:type>
		</nf:register>
		<nf:register>
			<nf:name>wildcard_hits</nf:name>
			<nf:description>Wildcard match hit counter</nf:description>
			<nf:type>generic_counter32</nf:type>
		</nf:register>
		<nf:register>
			<nf:name>exact_misses</nf:name>
			<nf:description>Exact match miss counter</nf:description>
			<nf:type>generic_counter32</nf:type>
		</nf:register>
		<nf:register>
			<nf:name>exact_hits</nf:name>
			<nf:description>Exact match hit counter</nf:description>
			<nf:type>generic_counter32</nf:type>
		</nf:register>
		<nf:register>
			<nf:name>num_pkts_dropped</nf:name>
			<nf:description>dropped packet counter</nf:description>
			<nf:type>openflow_output_queues_width</nf:type>
		</nf:register>
		<nf:register>
			<nf:name>dumy_software_0</nf:name>
			<nf:description>dummy software register</nf:description>
			<nf:type>generic_software32</nf:type>
		</nf:register>
		<nf:register>
			<nf:name>dumy_software_1</nf:name>
			<nf:description>dummy software register</nf:description>
			<nf:type>generic_software32</nf:type>
		</nf:register>
		<nf:register>
			<nf:name>timer</nf:name>
			<nf:description>timer</nf:description>
			<nf:type>generic_hardware32</nf:type>
		</nf:register>
	</nf:registers>
	<nf:constants>
		<nf:constant>
			<nf:name>:FAST_CLOCK_PERIOD</nf:name>
			<nf:value>8</nf:value>
		</nf:constant>
	</nf:constants>
	<nf:types>
		<nf:type xsi:type="nf:SimpleType">
			<nf:name>openflow_output_queues_width</nf:name>
			<nf:description>openflow_output_queues_width</nf:description>
			<nf:width>32*8</nf:width>
		</nf:type>
	</nf:types>
</nf:module>
