=== junganghu/netfpga_1g_httpGET/lib/xml/NF2_register_system.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.NetFPGA.org/NF2_register_system" targetNamespace="http://www.NetFPGA.org/NF2_register_system" elementFormDefault="qualified">

  <complexType name="Constant">
    <sequence>
      <element name="name" type="string" maxOccurs="1" minOccurs="1">
        </element>
      <element name="description" type="string" maxOccurs="1" minOccurs="0">
        </element>
      <element name="width" type="tns:Expression" maxOccurs="1" minOccurs="0">
        </element>
      <element name="value" type="tns:Expression" maxOccurs="1" minOccurs="1">
        </element>
    </sequence>
  </complexType>

  <complexType name="SimpleType">
    <complexContent>
      <extension base="tns:Type">
        <sequence>
          <element name="width" type="tns:Expression" maxOccurs="1" minOccurs="1">
            </element>
          <element name="bitmask" type="tns:BitmaskType" maxOccurs="unbounded" minOccurs="0">
            </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="BitmaskType">
    <complexContent>
      <extension base="tns:Type">
        <choice maxOccurs="1" minOccurs="1">
          <element name="pos" type="int" maxOccurs="1" minOccurs="1">
             </element>
          <sequence>
            <element name="pos_lo" type="int" maxOccurs="1" minOccurs="1">
               </element>
            <element name="pos_hi" type="int" maxOccurs="1" minOccurs="1">
               </element>
          </sequence>
        </choice>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="CompoundType">
    <complexContent>
      <extension base="tns:Type">
        <sequence>
          <element name="field" type="tns:Field" maxOccurs="unbounded" minOccurs="1"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="Field">
    <sequence>
      <element name="name" type="string" maxOccurs="1" minOccurs="1">
        </element>
      <element name="description" type="string" maxOccurs="1" minOccurs="0"/>
      <choice maxOccurs="1" minOccurs="1">
        <element name="type" type="string" maxOccurs="1" minOccurs="1">
          </element>
        <element name="width" type="tns:Expression" maxOccurs="1" minOccurs="1">
          </element>
      </choice>
    </sequence>
  </complexType>

  <complexType name="Type">
    <sequence>
      <element name="name" type="string" maxOccurs="1" minOccurs="1">
        </element>
      <element name="description" type="string" maxOccurs="1" minOccurs="0"/>
    </sequence>
  </complexType>

  <complexType name="TableType">
    <complexContent>
      <extension base="tns:Type">
        <sequence>
          <element name="depth" type="int" maxOccurs="1" minOccurs="1"/>
          <choice maxOccurs="1" minOccurs="1">
            <element name="entry_type" type="string" maxOccurs="1" minOccurs="1"/>
            <element name="width" type="tns:Expression" maxOccurs="1" minOccurs="1"/>
          </choice>
        </sequence>
        <attribute name="table_type">
          <simpleType>
            <restriction base="string">
              <enumeration value="indirect"/>
            </restriction>
          </simpleType>
        </attribute>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="Register">
    <sequence>
      <element name="name" type="string" maxOccurs="1" minOccurs="1">
        </element>
      <element name="description" type="string" maxOccurs="1" minOccurs="0">
        </element>
      <choice maxOccurs="1" minOccurs="0">
        <element name="type" type="string" maxOccurs="1" minOccurs="1">
          </element>
        <element name="width" type="tns:Expression" maxOccurs="1" minOccurs="1"/>
      </choice>
    </sequence>
  </complexType>

  <complexType name="RegisterList">
    <element name="register" type="tns:Register" maxOccurs="unbounded" minOccurs="0">
      </element>
    <element name="register_group" type="tns:RegisterGroup" maxOccurs="unbounded" minOccurs="0">
      </element>
  </complexType>

  <complexType name="Module">
    <sequence>
      <element name="name" type="string" maxOccurs="1" minOccurs="1">
        </element>
      <element name="prefix" type="string" maxOccurs="1" minOccurs="1">
        </element>
      <element name="location" maxOccurs="1" minOccurs="1">
        <simpleType>
          <restriction base="string">
            <enumeration value="core"/>
            <enumeration value="udp"/>
            <enumeration value="cpci"/>
          </restriction>
        </simpleType>
      </element>
      <element name="description" type="string" maxOccurs="1" minOccurs="0">
        </element>
      <element name="blocksize" type="string" maxOccurs="1" minOccurs="0">
        </element>
      <choice>
        <element name="preferred_base" type="tns:Address" maxOccurs="1" minOccurs="0">
          </element>
        <element name="force_base" type="tns:Address" maxOccurs="1" minOccurs="0">
          </element>
      </choice>
      <element name="registers" type="tns:RegisterList" maxOccurs="1" minOccurs="0"/>
      <element name="constants" type="tns:ConstantList" maxOccurs="1" minOccurs="0"/>
      <element name="types" type="tns:TypeList" maxOccurs="1" minOccurs="0"/>
      <element name="use_shared" type="string" maxOccurs="1" minOccurs="0"/>
        </element>
    </sequence>
  </complexType>

  <complexType name="RegisterGroup">
    <sequence>
      <element name="name" type="string" maxOccurs="1" minOccurs="1">
      	</element>
      <element name="description" type="string" maxOccurs="1" minOccurs="0">
        </element>
      <element name="instances" type="tns:Expression" maxOccurs="1" minOccurs="1">
      	</element>
      <element name="instance_size" type="tns:Expression" maxOccurs="1" minOccurs="0"/>
      <element name="register" type="tns:Register" maxOccurs="unbounded" minOccurs="0">
      	</element>
    </sequence>
  </complexType>

  <complexType name="Project">
    <sequence>
      <element name="name" type="string" maxOccurs="1" minOccurs="1">
        </element>
      <element name="description" type="string" maxOccurs="1" minOccurs="0">
        </element>
      <element name="version_major" type="int" maxOccurs="1" minOccurs="0">
        </element>
      <element name="version_minor" type="int" maxOccurs="1" minOccurs="0">
        </element>
      <element name="version_revision" type="int" maxOccurs="1" minOccurs="0">
        </element>
      <element name="dev_id" type="int" maxOccurs="1" minOccurs="0">
        </element>
      <element name="constants" type="tns:ConstantList" maxOccurs="1" minOccurs="0"/>
      <element name="types" type="tns:TypeList" maxOccurs="1" minOccurs="0"/>
      <element name="use_modules" type="string" maxOccurs="1" minOccurs="0">
        </element>
      <element name="memalloc" type="tns:MemoryAllocation" maxOccurs="1" minOccurs="1">
        </element>
    </sequence>
  </complexType>

  <attribute name="path" type="string"/>
  <simpleType name="Address">
    <restriction base="tns:hex"/>
  </simpleType>

  <complexType name="ConstantList">
    <sequence>
      <element name="constant" type="tns:Constant" maxOccurs="unbounded" minOccurs="0"/>
    </sequence>
  </complexType>

  <complexType name="TypeList">
    <sequence>
      <element name="type" type="tns:Type" maxOccurs="unbounded" minOccurs="0"/>
    </sequence>
  </complexType>

  <element name="module" type="tns:Module"/>
  <element name="project" type="tns:Project"/>

  <complexType name="Global">
    <sequence>
      <element name="constants" type="tns:ConstantList"/>
      <element name="types" type="tns:TypeList"/>
    </sequence>
  </complexType>

  <element name="global" type="tns:Global"/>

  <complexType name="Shared">
    <sequence>
      <element name="description" type="string" maxOccurs="1" minOccurs="0"/>
      <element name="constants" type="tns:ConstantList" maxOccurs="1" minOccurs="0"/>
      <element name="types" type="tns:TypeList" maxOccurs="1" minOccurs="0"/>
    </sequence>
  </complexType>

  <element name="shared" type="tns:Shared"/>

  <simpleType name="IntOrConstant">
    <union memberTypes="string int"/>
  </simpleType>

  <simpleType name="hex">
    <restriction base="string">
      <pattern value="0[xX][0-9a-fA-F]+"/>
    </restriction>
  </simpleType>

  <simpleType name="intOrHex">
    <union memberTypes="int tns:hex"/>
  </simpleType>

  <simpleType name="Expression">
    <restriction base="string"/>
  </simpleType>

  <simpleType name="MemoryLayout">
    <restriction base="string">
      <enumeration value="reference"/>
      <enumeration value="freeform"/>
      <enumeration value="cpci"/>
    </restriction>
  </simpleType>

  <complexType name="MemoryAllocation">
    <sequence>
      <element name="group" type="tns:MemoryAllocationGroup" maxOccurs="unbounded" minOccurs="0">
    		</element>
    </sequence>
    <attribute name="layout" type="tns:MemoryLayout" use="required"/>
  </complexType>

  <complexType name="MemoryAllocationGroup">
    <sequence>
      <element name="instance" type="tns:ModuleInstance" maxOccurs="unbounded" minOccurs="0">
    		</element>
    </sequence>
    <attribute name="name" type="string" use="required"/>
  </complexType>

  <complexType name="ModuleInstance">
    <attribute name="name" type="string" use="required"/>
    <attribute name="count" type="string" use="optional"/>
    <attribute name="base" type="tns:Address" use="optional"/>
  </complexType>
</schema>

=== junganghu/netfpga_1g_httpGET/projects/openflow_switch/include/wildcard_match.xml
<?xml version="1.0" encoding="UTF-8"?>
<nf:module xmlns:nf="http://www.NetFPGA.org/NF2_register_system" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.NetFPGA.org/NF2_register_system NF2_register_system.xsd ">
	<nf:name>wildcard_match</nf:name>
	<nf:prefix>openflow_wildcard_lookup</nf:prefix>
	<nf:location>udp</nf:location>
	<nf:description>wildcard match lookup</nf:description>
	<nf:blocksize>4096</nf:blocksize>
	<nf:registers>
		<nf:register>
			<nf:name>action</nf:name>
			<nf:description>openflow action field</nf:description>
			<nf:type>wildcard_action</nf:type>
		</nf:register>
		<nf:register>
			<nf:name>cmp_mask</nf:name>
			<nf:description>openflow entry-mask field</nf:description>
			<nf:type>wildcard_entry</nf:type>
		</nf:register>
		<nf:register>
			<nf:name>cmp</nf:name>
			<nf:description>openflow entry field</nf:description>
			<nf:type>wildcard_entry</nf:type>
		</nf:register>
		<nf:register>
			<nf:name>read_addr</nf:name>
			<nf:description>specifies which table to be read</nf:description>
			<nf:type>generic_software32</nf:type>
		</nf:register>
		<nf:register>
			<nf:name>write_addr</nf:name>
			<nf:description>specifies which table to be written</nf:description>
			<nf:type>generic_software32</nf:type>
		</nf:register>
		<nf:register>
			<nf:name>bytes_hit</nf:name>
			<nf:description>indicates how many bytes hit the table</nf:description>
			<nf:type>wildcard_counter</nf:type>
		</nf:register>
		<nf:register>
			<nf:name>pkts_hit</nf:name>
			<nf:description>indicates how many packets hit the table</nf:description>
			<nf:type>wildcard_counter</nf:type>
		</nf:register>
		<nf:register>
			<nf:name>dummy_1</nf:name>
			<nf:description>dummy software register</nf:description>
			<nf:type>generic_software32</nf:type>
		</nf:register>
		<nf:register>
			<nf:name>dummy_2</nf:name>
			<nf:description>dummy software regsiter</nf:description>
			<nf:type>generic_software32</nf:type>
		</nf:register>
		<nf:register>
			<nf:name>last_seen_ts</nf:name>
			<nf:description>last seen timestamps</nf:description>
			<nf:type>wildcard_counter</nf:type>
		</nf:register>
	</nf:registers>
	<nf:constants>
		<nf:constant>
			<nf:name>:OPENFLOW_WILDCARD_TABLE_SIZE</nf:name>
			<nf:value>32</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_WILDCARD_NUM_DATA_WORDS_USED</nf:name>
			<nf:value>:OPENFLOW_ACTION_WIDTH / :OPENFLOW_WILDCARD_TABLE_SIZE</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:OPENFLOW_WILDCARD_NUM_CMP_WORDS_USED</nf:name>
			<nf:value>:OPENFLOW_ENTRY_WIDTH / :OPENFLOW_WILDCARD_TABLE_SIZE + 1</nf:value>
		</nf:constant>
	</nf:constants>
	<nf:types>
		<nf:type xsi:type="nf:SimpleType">
			<nf:name>wildcard_action</nf:name>
			<nf:width>:OPENFLOW_ACTION_WIDTH</nf:width>
		</nf:type>
		<nf:type xsi:type="nf:SimpleType">
			<nf:name>wildcard_entry</nf:name>
			<nf:width>:OPENFLOW_ENTRY_WIDTH</nf:width>
		</nf:type>
		<nf:type xsi:type="nf:SimpleType">
			<nf:name>wildcard_counter</nf:name>
			<nf:width>:OPENFLOW_WILDCARD_TABLE_SIZE * 32</nf:width>
		</nf:type>
	</nf:types>
</nf:module>

=== junganghu/netfpga_1g_httpGET/projects/openflow_switch/include/header_parser.xml
<?xml version="1.0" encoding="UTF-8"?>
<nf:module xmlns:nf="http://www.NetFPGA.org/NF2_register_system" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.NetFPGA.org/NF2_register_system NF2_register_system.xsd ">
	<nf:name>header_parser</nf:name>
	<nf:prefix>header_parser</nf:prefix>
	<nf:location>udp</nf:location>
	<nf:description>Chop ether/IP/UDP-TCP header into 11 tuples</nf:description>
	<nf:blocksize>64</nf:blocksize>
	<nf:registers>
	</nf:registers>
	<nf:constants>
		<nf:constant>
			<nf:name>:ETH_TYPE_IP</nf:name>
			<nf:width>16</nf:width>
			<nf:value>0x0800</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:ETH_TYPE_ARP</nf:name>
			<nf:width>16</nf:width>
			<nf:value>0x0806</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:IP_PROTO_TCP</nf:name>
			<nf:width>8</nf:width>
			<nf:value>0x06</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:IP_PROTO_UDP</nf:name>
			<nf:width>8</nf:width>
			<nf:value>0x11</nf:value>
		</nf:constant>
		<nf:constant>
			<nf:name>:IP_PROTO_ICMP</nf:name>
			<nf:width>8</nf:width>
			<nf:value>0x01</nf:value>
		</nf:constant>
	</nf:constants>
	<nf:types>
	</nf:types>
</nf:module>

=== junganghu/netfpga_1g_httpGET/projects/openflow_switch/include/watchdog.xml
<?xml version="1.0" encoding="UTF-8"?>
<nf:module xmlns:nf="http://www.NetFPGA.org/NF2_register_system" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.NetFPGA.org/NF2_register_system NF2_register_system.xsd ">
	<nf:name>watchdog</nf:name>
	<nf:prefix>wdt</nf:prefix>
	<nf:location>udp</nf:location>
	<nf:description>Watchdog timer</nf:description>
	<nf:blocksize>256</nf:blocksize>
	<nf:registers>
		<nf:register>
		  <nf:name>enable_flg</nf:name>
			<nf:description>Watchdog timer enable flag</nf:description>
			<nf:type>generic_software32</nf:type>
		</nf:register>
		<nf:register>
		  <nf:name>counter</nf:name>
			<nf:description>Watchdog counter</nf:description>
			<nf:type>generic_hardware32</nf:type>
		</nf:register>
	</nf:registers>
	<nf:constants>
		<nf:constant>
			<nf:name>CPCI_REG_CTRL</nf:name>
			<nf:value>0x8</nf:value>
		</nf:constant>
	</nf:constants>
	<nf:types>
	</nf:types>
</nf:module>
